# Generated by Django 5.2.15 on 2026-06-05 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('C', 'C'), ('C++', 'C++'), ('JavaScript', 'JavaScript'), ('Go', 'Go')], max_length=20)),
                ('source_code', models.TextField()),
                ('detected_errors', models.TextField()),
                ('explanation', models.TextField()),
                ('corrected_code', models.TextField()),
                ('best_practices', models.TextField()),
                ('confidence_score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analysis_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
