# Generated by Django 5.2.15 on 2026-06-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysishistory',
            name='best_practices',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='analysishistory',
            name='corrected_code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='analysishistory',
            name='detected_errors',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='analysishistory',
            name='explanation',
            field=models.TextField(blank=True),
        ),
    ]
