# Generated by Django 5.2.15 on 2026-06-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_analysis', '0002_alter_analysishistory_best_practices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysishistory',
            name='raw_response',
            field=models.TextField(blank=True),
        ),
    ]
