# Generated by Django 5.2.15 on 2026-06-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_analysis', '0003_analysishistory_raw_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysishistory',
            name='analysis_duration_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysishistory',
            name='report_download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
