# Generated by Django 5.2.15 on 2026-06-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_analysis', '0004_analysishistory_analysis_duration_ms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysishistory',
            name='analysis_status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=20),
        ),
    ]
