"""
PDF report generation service.
"""

from io import BytesIO

from reportlab.lib.styles import (
    ParagraphStyle,
    getSampleStyleSheet,
)

from reportlab.platypus import (
    Paragraph,
    Preformatted,
    SimpleDocTemplate,
    Spacer,
)


class PDFReportService:

    @staticmethod
    def generate_analysis_report(
        analysis,
    ):

        buffer = BytesIO()

        doc = SimpleDocTemplate(
            buffer,
        )

        styles = getSampleStyleSheet()

        code_style = ParagraphStyle(
            "Code",
            parent=styles["BodyText"],
            fontName="Courier",
            fontSize=9,
            leading=12,
        )

        elements = []

        elements.append(
            Paragraph(
                "AI Code Analysis Report",
                styles["Title"],
            )
        )

        elements.append(
            Spacer(
                1,
                20,
            )
        )

        metadata = [
            (
                "Report ID",
                analysis.id,
            ),
            (
                "Language",
                analysis.language,
            ),
            (
                "Confidence Score",
                f"{analysis.confidence_score}%",
            ),
            (
                "Analysis Duration",
                f"{analysis.analysis_duration_ms} ms",
            ),
            (
                "Created At",
                str(
                    analysis.created_at
                ),
            ),
        ]

        for label, value in metadata:

            elements.append(
                Paragraph(
                    f"<b>{label}:</b> {value}",
                    styles["BodyText"],
                )
            )

        elements.append(
            Spacer(
                1,
                20,
            )
        )

        # ---------------------------------
        # Detected Errors
        # ---------------------------------

        elements.append(
            Paragraph(
                "Detected Errors",
                styles["Heading2"],
            )
        )

        elements.append(
            Paragraph(
                analysis.detected_errors,
                styles["BodyText"],
            )
        )

        elements.append(
            Spacer(
                1,
                15,
            )
        )

        # ---------------------------------
        # Explanation
        # ---------------------------------

        elements.append(
            Paragraph(
                "Explanation",
                styles["Heading2"],
            )
        )

        elements.append(
            Paragraph(
                analysis.explanation,
                styles["BodyText"],
            )
        )

        elements.append(
            Spacer(
                1,
                15,
            )
        )

        # ---------------------------------
        # Corrected Code
        # ---------------------------------

        elements.append(
            Paragraph(
                f"Corrected Code ({analysis.language})",
                styles["Heading2"],
            )
        )

        elements.append(
            Preformatted(
                analysis.corrected_code,
                code_style,
            )
        )

        elements.append(
            Spacer(
                1,
                15,
            )
        )

        # ---------------------------------
        # Best Practices
        # ---------------------------------

        elements.append(
            Paragraph(
                "Best Practices",
                styles["Heading2"],
            )
        )

        elements.append(
            Paragraph(
                analysis.best_practices,
                styles["BodyText"],
            )
        )

        elements.append(
            Spacer(
                1,
                20,
            )
        )

        elements.append(
            Paragraph(
                "Generated by AI-Powered Multi-Language Code Error Detection and Explanation System -Developed by Indra",
                styles["Italic"],
            )
        )

        doc.build(
            elements
        )

        pdf = buffer.getvalue()

        buffer.close()

        return pdf